### ISSUE TITLE
Increase endTime by e.g. 30 days

### ISSUE THREAD

**Issue by wardbeyens** [CoolCoderSJ/HCGateway#12]
**Is your feature request related to a problem? Please describe.**

The problem is that `Samsung Health` has 1 record per day for the amount of steps that is updated.
The end time for that record is 23:59.
I think [this](https://github.com/CoolCoderSJ/HCGateway/blob/9c5c99580f97e1614c9376179157eb22cb25e789/app/App.js#L163-L167) is why.
`oprator: between`
`endTime: String(new Date().toISOString()` 
so endTime is now. So that is why this record is not found.

**Describe the solution you'd like**

Increase endTime by e.g. 30 days

**Additional context**
![image](https://github.com/user-attachments/assets/23c7b8b4-8ae8-4611-b4ca-46d87682c50d)

**Comment by CoolCoderSJ** [comment]
I use Samsung Health as well- this is not a problem
The block of code you linked fetches all data from the past 30 days up to today- since the start time for the data is still within today, it still syncs the data. If you are using a custom query to fetch the data you may need to adjust this on your own part. Otherwise, you should see your data.

Here's an example using my real data:
```
curl --location 'https://api.hcgateway.shuchir.dev/api/fetch/steps' \
--header 'Content-Type: application/json' \
--data '{
    "userid": "<redacted>"
}'
```
Response:
```json
[
    ...
    {
        "$collectionId": "steps",
        "$createdAt": "2024-10-11T21:52:13.774+00:00",
        "$databaseId": "<redacted>",
        "$id": "0f747ef1-c6a9-4ba6-939b-d5ce42e27dc0",
        "$permissions": [],
        "$updatedAt": "2024-10-11T21:52:17.810+00:00",
        "app": "com.sec.android.app.shealth",
        "data": {
            "count": 7825
        },
        "end": "2024-10-12T03:59:59.999+00:00",
        "id": "0f747ef1-c6a9-4ba6-939b-d5ce42e27dc0",
        "start": "2024-10-11T04:00:00.000+00:00"
    }
]
```
